name = "yuzu-web"
compatibility_date = "2024-11-06"
account_id = "ec96c85e8eae01bdf4c37e6ce90a7cce"

assets = { directory = "build" }

[env.staging]
name = "yuzu-web-staging"
routes = [{ pattern = "yuzu-web-staging.r8edev.xyz", custom_domain = true }]