name = "yuzu-api"
main = "src/server.ts"
compatibility_date = "2024-11-06"
account_id = "ec96c85e8eae01bdf4c37e6ce90a7cce"
observability = { enabled = true }

[env.staging]
name = "yuzu-api-staging"
routes = [
  { pattern = "yuzu-api-staging.r8edev.xyz", custom_domain = true }
]

[env.production]
name = "yuzu-api-production"
routes = [
  { pattern = "yuzu-api-production.r8edev.xyz", custom_domain = true }
]
