name = "yuzu-api"
main = "src/index.ts"
compatibility_date = "2024-11-06"
account_id = "ec96c85e8eae01bdf4c37e6ce90a7cce"

[env.staging]
name = "yuzu-api-staging"
routes = [{ pattern = "yuzu-api-staging.r8edev.xyz", custom_domain = true }]