[profile.default]
solc_version = "0.8.20"
evm_version = "paris"
auto_detect_solc = true
optimizer = true
optimizer_runs = 200

src = "src"
out = "out"
libs = ["lib"]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
ignored_warnings_from = ["lib"]

remappings = [
  "ds-test/=lib/forge-std/lib/ds-test/src/",
  "forge-std/=lib/forge-std/src/",
  "oz/=lib/openzeppelin-contracts/contracts/"
]
