name: Deploy Web to Production

on:
  push:
    branches: [production]
    paths:
      - ".github/workflows/deploy-web-production.yml"
      - "packages/web"

jobs:
  deploy-web-production:
    runs-on: r8e

    defaults:
      run:
        working-directory: ./packages/web

    environment:
      name: production
      url: https://yuzu-web.r8edev.xyz

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        id: pnpm-install
        with:
          run_install: false

      - name: Get PNPM Store Directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup PNPM Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Configure PNPM
        run: pnpm config set auto-install-peers true

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
        env:
          VITE_API_URL: https://yuzu-api-production.r8edev.xyz
          VITE_CONTRACTS_ENV: mainnet
          VITE_TURSTILE_SITEKEY: 0x4AAAAAAA5IlFlKQRFnSj_Z
          VITE_APP_PUBLIC_POSTHOG_KEY: phc_RqR1UiObCu0GaFL2Rs2VOBZwTjneg3fr0Fuz4yVQgbl
          VITE_APP_PUBLIC_POSTHOG_HOST: https://us.i.posthog.com

      - name: Deploy
        run: pnpm run deploy:production
        env:
          CLOUDFLARE_API_TOKEN: "${{ secrets.CLOUDFLARE_API_TOKEN }}"
