name = "yuzu-indexer"
main = "src/index.ts"
compatibility_date = "2024-09-25"
account_id = "ec96c85e8eae01bdf4c37e6ce90a7cce"
workers_dev = true
triggers = { crons = ["* * * * *"] }
observability = { enabled = true }

[env.staging]

[env.production]
