name = "yuzu-indexer"
main = "src/index.ts"
compatibility_date = "2024-10-22"
account_id = "ec96c85e8eae01bdf4c37e6ce90a7cce"
workers_dev = true
observability = { enabled = true }
workflows = [{ name = "schedule", binding = "SCHEDULE", class_name = "ScheduleWorkflow" }]

[env.staging]
workflows = [{ name = "schedule-staging", binding = "SCHEDULE", class_name = "ScheduleWorkflow" }]

[env.production]
workflows = [{ name = "schedule-prod", binding = "SCHEDULE", class_name = "ScheduleWorkflow" }]
